
[project]
name = "mpc-class-01"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.134.0",
    "mcp[cli]>=1.26.0",
    "starlette>=0.52.1",
    "uvicorn>=0.41.0",
]
